[Jee] Step2 - 카드 클래스 구현하기
codesquad-members-2022/swift-pokergame pull request #20
Opened 2022-02-21 14:43 UTC by Dihee

:pencil2: **Step 2 작업 목록**

- [x]  카드 클래스 생성 (객체지향 프로그래밍 방식에 충실하게!)
- [x] 속성 값에 모양 4, 숫자 12개 (각 데이터 구조로 표현)
- [x] 문자열로 반환하는 함수 구현
- [x] 문자열 1은 A로, 11은 J로, 12는 Q로, 13은 K로 출력
- [x] 객체 인스턴스 생성 및 콘솔 출력

<br>

:pencil2: **학습 키워드**

* 객체지향 프로그래밍
* 유니코드

<br>

:pencil2: **고민과 해결**

객체지향 프로그래밍을 할 때, 각 각 분리 작업하는 방법을 학습했으나 잊어버렸습니다.
이번에 다시 학습하였고, 학습한대로 구현 및 잊지 않도록 리드미에 적어두었습니다.

<img width="379" alt="스크린샷 2022-02-21 오후 11 18 55" src="https://user-images.githubusercontent.com/92635121/154977085-9297b7f1-86db-4603-a15e-e480ea36de80.png">

2022-02-21 23:36 UTC, godrm requested changes
Card 부분은 수정해서 다시 Push해보세요

2022-02-21 23:36 UTC, godrm commented on PokerGame/PokerGame/Card.swift
> +    let number: Int
Shape는 타입을 선언했는 number는 Int로 되어 있네요
enum 타입으로 선언해도 되지않을까요?

2022-02-21 23:36 UTC, godrm commented on PokerGame/PokerGame/Card.swift
> +        print(shape.rawValue + numberConvert(number: number))
로직을 구현하는 곳에서 직접 출력하는 코드는 넣으면 안됩니다
값을 리턴하도록 구현하는 게 좋습니다

2022-02-21 23:36 UTC, godrm commented on PokerGame/PokerGame/Card.swift
> +        }
스위프트는 description 이라는 것으로 문자열을 만드는 데, CustomStringConvertible 프로토콜을 확인해보세요

2022-02-21 23:36 UTC, godrm commented on PokerGame/PokerGame/ViewController.swift
>              imageView.frame = CGRect(x: positionX, y: 50, width: width - 3, height: hight)
여기서 50 이나 -3 같은것을 주석으로 설명하지 말고, 코드로 표현해보세요
상수나 변수로 그 의미를 전달하는 것도 중요합니다

2022-02-22 10:07 UTC, godrm commented
엇.. 무슨일 있는거 아니죠? 어제 이후로 Push가 안올라와서 남겨봅니다.

2022-02-22 11:23 UTC, Dihee commented
> 엇.. 무슨일 있는거 아니죠? 어제 이후로 Push가 안올라와서 남겨봅니다.

JK 😌 Xcode 오류로 상당시간 허비하고, 구현에 switch문 넣는 과정이 어려워 오래걸렸습니당 ㅠ3ㅠ

2022-02-22 13:27 UTC, godrm commented on PokerGame/PokerGame/Card.swift
> +        }
description은 CustomStringConvertible 프로토콜을 채택하도록 구현해야 합니다. 
선언부는 다른 점이 있는 프로토콜을 다뤄야 하는 게 포인트입니다. 다음 단계를 하기 전에 그 부분을 개선해보세요

2022-02-22 13:27 UTC, merged

2022-02-23 02:07 UTC, Dihee commented on PokerGame/PokerGame/Card.swift
> +        }
넵 수정해서 다음 PR에 적용하겠습니다! 감사합니다!