[Jed] Step 2-3 : 카드덱 구현하고 테스트하기
codesquad-members-2022/swift-pokergame pull request #32
Opened 2022-02-22 07:26 UTC by junu0516

## 작업 내용
- [x] 기존 2단계 피드백 반영하여 Card 클래스 수정
- [x] 카드덱 구조체 구현
    - [x] count, shuffle, removeOne, reset 각각 구현
    - [x] 상위모듈에서 카드덱 기능 확인을 위한 테스트 메소드 작성    
 
## 학습 키워드
- mutating
- CaseIterable, allCases
- Knuth Shuffle

## 고민과 해결
- CardDeck 구조체의 프로퍼티로 deck, count 두 개를 가지고 있는데, 외부에서 deck에는 직접 접근하지 못해야 하고 count는 읽기만 가능해야 하기 때문에 접근제어자를 아래와 같이 선언했습니다.
```swift
 private var deck: [Card] = []
 private (set) var count: Int = 0
```
- 여기서 덱에 카드를 넣는 동작은 reset()에서 실행하도록 하고, 생성자 호출 시 reset()을 호출하도록 했습니다.
    - 이 경우 생성자에서 기존 프로퍼티 값을 바꾸는 메소드를 호출하기 위해서는 stored property의 값이 이미 초기화된 상태여야하기 때문에 위와 같이 프로퍼티 선언 시에 각각 빈 배열과 0의 값을 가지도록 했습니다. 
- 덱에서 카드를 빼는 동작은 배열의 removeLast() 메소드를 내부적으로 호출하도록 했습니다.
    - removeFirst()로 할 경우에는 배열의 맨 처음 요소를 제거하면서 나머지 요소들의 인덱스를 한칸씩 앞으로 빼는 연산을 수행해야 하므로 비효율적일 것이라 판단했습니다. 
```swift
mutating func removeOne()-> Card{
   count -= 1
   return deck.removeLast()
}
```

2022-02-22 08:46 UTC, godrm requested changes
다음 내용들 간단하니까 확인해서 수정해서 Push해보세요

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        self.number = number
그러네요. 카드 객체가 깔끔해졌네요. 
근데 이 init?() 부분에서 어떤 부분이 실패할 수 있는 걸까요?

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +    private (set) var count: Int = 0
count는 deck.count와 같은 값일까요? 다른 값일까요?
동일한 값이면 별도로 있어야 할까요?

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        for i in 0..<deck.count-1{
`i` 같은 관용적인 표현도 의미있는 단어로 표현해주세요.

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        return deck.removeLast()
만약에 deck에 카드가 없으면 어떻게 되나요?

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        self.deck = []
deck에 [] 빈 배열을 넣는것과 removeAll()을 호출하는 것은 어떤 차이가 있을까요?

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +                print("테스트 종료")
테스트 함수에서도 print를 출력할 필요는 없습니다.
대신 XCTAssert- 계열 함수로 어떤 값인지 아닌지 비교해서 처리하는 게 중요합니다.

2022-02-22 08:46 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
>                  printCard(card)
Card.Suit.allCases를 활용한다면 index 없이도 순회하거나 random 값에 접근할 수 있지 않을까요?

2022-02-22 13:53 UTC, junu0516 commented on PokerGameApp/PokerGameApp/Card.swift
> +        self.number = number
```swift
init?(cardSuitindex: Int, cardNumber: Int){
      if(cardSuitindex>=Suit.allCases.count || cardNumber<=0 || cardNumber > 13){
          return nil
      }
      self.suit = Suit.allCases[cardSuitindex]
      self.number = Number(cardNumber)
}
```
위처럼 작성한 후, Card.Number을 수정하면서 생성자의 첫 if문을 제거하는 과정에서 ?를 제거하는 것을 깜빡했습니다! 바로 수정하겠습니다.

2022-02-22 13:55 UTC, junu0516 commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +    private (set) var count: Int = 0
count는 deck.count와 같은 값입니다. 해당 변수가 항상 deck.count를 리턴하도록 수정하려고 합니다!
```swift
 var count: Int{
    return deck.count
 }
```

2022-02-22 14:09 UTC, junu0516 commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        return deck.removeLast()
빈 배열일 때 removeLast()를 호출하면 컴파일 에러가 난다고 나오네요! 옵셔널을 리턴하는 popLast()로 수정했습니다.
대신 외부에서 Card.removeOne 값을 받을 때 nil 여부를 체크하도록 했습니다.

2022-02-22 14:13 UTC, junu0516 commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        self.deck = []
removeAll()을 호출하면 기존에 남아있던 카드의 수(deck의 길이)에 비례하여 remove해야 하기 때문에 결과적으로 시간복잡도가 O(N)이 될 것이라고 생각했습니다.
이럴 경우에 아얘 빈 배열을 변수에 할당하면 O(N)의 연산을 수행하지 않아도 될 거라고 생각했는데 맞게 판단한걸까요?

2022-02-22 14:19 UTC, junu0516 commented on PokerGameApp/PokerGameApp/ViewController.swift
>                  printCard(card)
index가 아닌 allCases 배열의 randomElement()를 사용하는 식으로 수정했습니다.

2022-02-22 14:31 UTC, junu0516 commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        self.deck = []
> deck에 [] 빈 배열을 넣는것과 removeAll()을 호출하는 것은 어떤 차이가 있을까요?

테스트 메소드 제외하고 나머지 피드백 주신 부분 모두 반영해서 수정했습니다!
XCTAssert 사용하는 부분은 단위테스트 공부해서 다음단계에서 같이 진행해도 될까요?
추가로 위에서 deck에

2022-02-22 14:32 UTC, junu0516 commented
테스트 메소드 제외하고 나머지 피드백 주신 부분 모두 반영해서 수정했습니다!
XCTAssert 사용하는 부분은 단위테스트 공부해서 다음단계에서 같이 진행해도 될까요?

추가로 위에서 deck에 빈 배열을 할당하는 것과 removeAll()을 호출하는 것의 차이를 말씀하셔서 제가 생각한 부분을 코멘트 남겼는데 맞게 판단한걸까요?

2022-02-23 01:52 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        self.deck = []
댓글이 다 안보이는데 제가 이상한건가 모르겠는데 다시 확인해봐주세요

2022-02-23 01:55 UTC, godrm commented
> 테스트 메소드 제외하고 나머지 피드백 주신 부분 모두 반영해서 수정했습니다!
> 
> XCTAssert 사용하는 부분은 단위테스트 공부해서 다음단계에서 같이 진행해도 될까요?

합쳐서 여기에 쓰기보다 개별 댓글에 남겨주는 게 맥락을 이해하고 답변하기 좋습니다. 
테스트는 다음 단계에서 해보세요

> 추가로 위에서 deck에 빈 배열을 할당하는 것과 removeAll()을 호출하는 것의 차이를 말씀하셔서 제가 생각한 부분을 코멘트 남겼는데 맞게 판단한걸까요?

제가 맞고 틀리고의 문제가 아닙니다. 본인이 기준을 정하고 근거를 갖고 저를 설득하려고 해보세요. 코멘트가 짤렸더군요

2022-02-23 01:55 UTC, merged

2022-02-23 02:04 UTC, junu0516 commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        self.deck = []
댓글 수정하면서 잘못된 내용이 들어갔던 것 같습니다! 지금 다시 수정했어요