[Rosa] Step2 - 카드 객체 구현
codesquad-members-2022/swift-pokergame pull request #34
Opened 2022-02-22 07:28 UTC by Jinsujin

### 작업 목록
- [x] 카드 데이터를 추상화해서 객체로 구현하고 단계별로 다양한 상황에 확장해서 사용한다.
- [ ] 객체 이름, 변수 이름, 함수 이름에서 자신만의 규칙을 만든다.
  - 아직 네이밍 규칙을 만들지 못했습니다. 조금 더 고민해 보겠습니다.
- [x] 임의의 카드 객체 인스턴스를 하나 만들어서 출력한다.

### 학습 키워드 
- Swift Style Guide

### 고민과 해결
- 네이밍을 짓는데 많은 고민이 됩니다. 
  - 제가 만드는 입장에서는 배경에 대해 알고 있으니 설명을 빠뜨리게 되는 것 같습니다.
  - 코드를 사용하는 입장에서 한번 더 생각해 보고 있습니다.
  - 무의식 적으로 알고 있는 단어를 주로 사용하는 것 같습니다. 사전이나 관련된 배경지식을 틈틈히 보면서 어떤 단어가 적합한지 비교해 보는 시간이 필요할 것 같습니다.
- 작업에 집중할 수록 커밋을 자주 안한다는 사실을 알았습니다.
  - 의식적으로 기능단위로 쪼개어 커밋하겠습니다.

2022-02-22 08:48 UTC, godrm commented
한 가지 팁을 주자면, 커밋할 내용을 미리 정해놓고 작업하면 그것만 집중하고 완료하면 커밋할 수 있습니다. 
무엇에 집중해야 하는지 고민하고 시작해보세요

2022-02-22 08:51 UTC, godrm requested changes
아래 피드백을 확인해보시고, 카드 관련 부분을 수정해보세요.

2022-02-22 08:51 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        }
이 부분은 두 가지 의견이 있습니다. 
- 하나는 String으로 만드는 것은 CustomStringConvertible 프로토콜을 적용해보세요. 가장 많이 쓰는 것중에 하나입니다
- fatalError()는 앱이 멈춰버리는 코드라서 사용하지 않기를 추천합니다. 아주 치명적인 경우만 쓰는 데 개인적으로는 그래도 쓰지 말라고 합니다.

2022-02-22 08:51 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        return self.suit.rawValue + self.numberToString()
Suit 도 CustomStringConvertible 프로토콜을 채택할 수 있습니다. 
지금 보니 numberToString()은 number의 정보표현이네요. 이렇게 된 이유는 number 의 타입이 Int라서 그렇습니다.
Suit처럼 하위 타입으로 만들어보세요. 그러면 코드를 옮길 수 있습니다.

2022-02-22 08:51 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let spade7 = Card(suit: .spade, number: 7)
특히 number가 Int라면 치명적인 부분이 0, 100, 1234 같은 값이 들어갈 수 있게 됩니다. 그런 카드가 어떻게 될까요? 생성이 되야 할까요? 타입에 대해 고민은 범위를 고민하는 것에서 시작합니다.

2022-02-23 02:16 UTC, Jinsujin commented on PokerGameApp/PokerGameApp/Card.swift
> +        }
객체를 잘 못 생성하는 것만으로 앱을 멈추게 하는건 좋지 않겠네요 
앞으로 사용에 주의하겠습니다!

2022-02-23 02:19 UTC, Jinsujin commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let spade7 = Card(suit: .spade, number: 7)
숫자값 또한 enum 으로 처리하면 허락된 범위내에서 객체를 생성할 수 있겠네요. 
그럼 범위를 벗어난 경우에도 처리가 가능해지므로 코드를 사용하는 사용자가 안전하게 객체를 생성할 수 있을것 같습니다.
범위에 대해서 항상 고민해보겠습니다!

2022-02-23 02:20 UTC, Jinsujin commented on PokerGameApp/PokerGameApp/Card.swift
> +        return self.suit.rawValue + self.numberToString()
CustomStringConvertible 을 채택하면 좀 더 명확한 코드가 되겠네요. 수정하겠습니다😊

2022-02-23 02:50 UTC, Jinsujin commented
> 리뷰받은 부분 다시 수정해서 Push 했습니다, 확인 부탁드립니다!

- CustomStringConvertible 을 Card 와 nested enum 인 Suit, Number 에 적용했습니다
- 출력은 각각의 타입에서 결정하도록 변경 했습니다.
- Number 를 enum 으로 정의하여 지원하는 범위값만으로 객체를 생성할 수 있도록 변경했습니다 

커밋 내용을 미리 생각해 보니, 코드 구현을 한번 더 생각해 볼 수 있어서 좋았습니다!
좋은 팁 감사합니다 JK~🥰

2022-02-23 05:40 UTC, merged