[Eddy] Step 3: CardDeck 객체 구현
codesquad-members-2022/swift-pokergame pull request #35
Opened 2022-02-22 08:04 UTC by BumgeunSong

**작업 목록**

- [ ] CardDeck `struct` 추가
- [ ] CardDeck `init` 구현
- [ ] `shuffle` method 구현 (in-place / Fisher-Yates shuffle )
- [ ] `draw` method 구현 
- [ ] `reset` method 구현
- [ ] viewController에 `testCardDeck` 구현

**학습 키워드**
- Class vs Struct
- Reference type은 Heap에, Value type은 Stack에 저장됨.
- Debug 할 때 메모리 주소 확인 (Reference type의 경우 변수명 옆에 표시)

- Fisher-Yates shuffle
- Case Iterable

- access control 키워드 
   - private: 해당 타입의 괄호 안에서만 접근 가능
   - fileprivate: 해당 타입이 정의된 소스 파일 안에서만 접근 가능
   - internal: 모듈 안에서만 접근 가능. 기본값.
   - public: 모듈 바깥에서도 접근 가능.
   - open: 퍼블릭과 범위는 같지만, override가 가능함.

- popLast() vs removeLast()

**고민과 해결**
- reset() 함수 구현.
   - 처음에는 reset을 할 때마다 initializer와 똑같이 52개 카드를 생성해서 초기화했습니다.
   - reset을 여러번 할 경우 불필요하게 카드를 계속 생성하는 것 같아서, defaultCards를 별도로 저장하고 해당 프로퍼티와 shuffle을 사용해 초기화하도록 구현했습니다.
   - 그럼에도 불구하고 reset 메소드 자체가 struct스럽지 않다는 점이 뭔가 찜찜했습니다. 
   - 사실 현재 CardDeck은 cards 프로퍼티 데이터밖에 없습니다. 어차피 불변값인 struct의 특성상, reset()보다는 상위 모듈에서 init을 다시 해서 사용하는 것이 자연스럽다고 생각했습니다. 
   - 하지만 일단 요구사항에 reset()이 있었기 때문에 현재 상태로 구현했습니다.

- popLast와 removeLast의 차이
   - 여태 removeLast를 별 생각없이 썼었는데, 만약 empty array일 경우 crash를 일으킨다는 사실을 알게 되었습니다.
   - optional을 return하는 popLast로 바꿔서 해결했습니다.

2022-02-22 08:56 UTC, godrm requested changes
전체적으로 깔끔하네요. 
다음 피드백을 확인해보고 개선해보세요

2022-02-22 08:56 UTC, godrm commented on PockerGameApp/PockerGameApp/CardDeck.swift
> +        shuffle()
init()과 아래 reset() 내용이 중복이 많네요. 코드가 반복된다면 하위 함수로 분리할 수 있다는 것을 의미합니다. 개선해보세요
-
덧붙여서 생성하고 나서 shuffle()을 하느냐 안하느냐가 포함되는 게 좋을까요? 별도로 부르는 게 좋을까요?
CardDeck을 생성하고 호출하는 입장에서도 고민해보세요

2022-02-22 08:56 UTC, godrm commented on PockerGameApp/PockerGameApp/CardDeck.swift
> +            cards.swapAt(i, roll)
오 스왑함수를 쓰셨네요! 깔끔하네요 
다만 i 도 roll 처럼 의미있는 단어로 바꿔서 표현해보세요

2022-02-22 08:56 UTC, godrm commented on PockerGameApp/PockerGameApp/CardDeck.swift
> +            "\(partialResult) \(card)"
좋은 시도네요. 다만 이미 Array가 CustomStringConvertible을 채택하고 있어서 배열에 있는 카드 정보를 표시해줄 수 있습니다. 참고하세요

2022-02-22 08:56 UTC, godrm commented on PockerGameApp/PockerGameApp/ViewController.swift
> +        print(deck)
테스트 함수는 약간 규칙이 있습니다. print로 값을 확인하기 보다는 XCTAssert-계열 함수로 기대하는 값을 확인하는 게 규칙입니다.
여기 있는 print 대신에 Assert 계열로 바꿔보세요

2022-02-23 02:36 UTC, BumgeunSong commented on PockerGameApp/PockerGameApp/CardDeck.swift
> +        shuffle()
**중복**
- `defaultCards`를 사용해서 중복을 최소화했습니다!

**생성 후 shuffle()**
- 처음에는 '당연히 Shuffle한 Deck이 기본이다'라는 것이 상식이라고 생각했습니다. 
- 하지만 고민해보니, 기본으로는 정렬된 상태의 덱을 return 하는 것이 낫다고 판단되었습니다.
-  클라이언트는 shuffle이 initializer에 구현되어있다는 점을 알고 있어야 하는데 이러면 결합도가 높아집니다.
- shuffle은 public interface이므로 필요하면 상위 모듈이 사용하게 하도록 만들고, 기본 생성자 함수에서는 빼는 게 행동을 예측하는데 더 효과적일 거 같다는 생각이 들었습니다.
- 해당 내용으로 변경했습니다!

2022-02-23 02:36 UTC, BumgeunSong commented on PockerGameApp/PockerGameApp/CardDeck.swift
> +            "\(partialResult) \(card)"
그 편이 더 깔끔하겠네요! 수정했습니다 :)

2022-02-23 02:37 UTC, BumgeunSong commented on PockerGameApp/PockerGameApp/ViewController.swift
> +        print(deck)
XCT Target을 쓰지 않으려고 하다보니 print를 사용했었습니다.
XCT Target을 추가하고 test code를 써보았습니다!

2022-02-23 02:38 UTC, godrm commented on PockerGameApp/PockerGameApp/CardDeck.swift
> +            cards.swapAt(i, roll)
이 부분이 남았는데 다음에도 계속 개선해보세요

2022-02-23 02:38 UTC, merged

2022-02-23 02:39 UTC, BumgeunSong commented on PockerGameApp/PokerGameAppTests/PokerGameAppTests.swift
> +    }
현재는 일단 정렬되지 않은 상태를 가지면 통과하도록 했는데요. 랜덤성을 가진 함수를 어떻게 테스트해야할지 고민이 되었습니다. Stack overflow을 찾아보니 randomness는 unit test의 대상이 아니라는 말도 보았는데... 이해를 잘 하진 못했습니다ㅜ

2022-02-23 02:42 UTC, godrm commented on PockerGameApp/PokerGameAppTests/PokerGameAppTests.swift
> +    }
맞아요 셔플 자체는 테스트하기 어렵습니다. 
그래서 이런 제네레이터를 활용하는 편입니다 https://developer.apple.com/documentation/swift/int/3020586-random