[dale] - Step3-1 카드덱구현하기
codesquad-members-2022/swift-pokergame pull request #39
Opened 2022-02-22 09:28 UTC by sungju-kim

- [x]  카드덱 구현
- [x]  갯수반환 count 구현
- [x]  랜덤하게 섞는 shuffle 구현
- [x]  카드 인스턴스중에 하나를 반환하고 목록에서 삭제 구현
- [x]  모든 카드를 채워넣는 reset 구현
- [ ]  테스트 코드 작성

## 고민

1. tempCardArr라는 변수를 생성해야하나 말아야하나 고민을 하다가 originCards 를 var 가 아닌 let으로 선언하고 싶어 tempCardArr라는 변수를 만들고 카드를 담는데 이용했습니다.
2. 테스트를 활용하고 싶으나 아직 이해도가 높지않아 시도중입니다. - 미해결

## 질문

shuffle 함수 구현시 randomElement 메소드를 사용했는데, 이 이부분까지 직접 구현을 해야하는지 궁금했습니다.

2022-02-22 09:37 UTC, godrm requested changes
파일 분리해보시고 변수 이름 정도는 수정해서 push해보세요

2022-02-22 09:37 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +}
Card 파일에 CardDeck까지 포함되어 있네요. 기본적으로 타입이 다르면 파일도 분리하시는 게 좋습니다.

2022-02-22 09:37 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        originCards = tempCardArr
변수 이름에 -arr나 -str 이런 타입을 붙이지 말고 그 역할을 그대로 쓰세요
여기서는 originCards에 직접 append 해도 되지 않을까요?

2022-02-22 09:37 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeckTest.swift
> +import Foundation
단위 테스트를 추가했으니, 테스트 함수를 추가해서 Card 객체를 생성해보는 것부터 시작해보세요

2022-02-22 09:37 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +            guard let randomIndex = (i..<self.count).randomElement() else {continue}
`.randomElement()` 까지 직접 구현할 필요는 없습니다. 나중에도 대부분은 Array.shuffle()을 그냥 쓸겁니다

2022-02-22 09:37 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +            for j in Card.Number.allCases{
tempCardArr, i, j 같은 변수도 좀 더 의미있는 역할을 표현하는 영단어로 바꿔보세요. 
코드를 읽는 사람에게 정보를 줄 수 있는 중요한 수단입니다.

2022-02-23 05:38 UTC, sungju-kim commented on PokerGameApp/PokerGameApp/Card.swift
> +            for j in Card.Number.allCases{
수정했습니다! 테스트 처음 해봤는데 신기합니다!!

2022-02-23 05:41 UTC, godrm commented on PokerGameApp/CardDeckTest/CardDeckTest.swift
> +        XCTAssertNotEqual(cardDeck1, cardDeck2, "일치하지 않습니다.")
랜덤하게 섞는 shuffle 자체는 테스트하기 꽤 까다롭습니다
확률적으로 이전 상태와 같아도 썩이긴 한거니까요 
이렇게 직접 비교하기 보다는 generator라는 것을 두고 같은 방식으로 섞으면 같아지는 지 볼 수도 있습니다
이 방법은 어쩔때는 실패할 수 있습니다. 참고하세요

2022-02-23 05:41 UTC, merged