[Chez] Step2 - Card 클래스 구현
codesquad-members-2022/swift-pokergame pull request #41
Opened 2022-02-22 11:30 UTC by asqw887

### **🟢 작업 목록**

- [x]  Card 클래스 구현
    - [x]  symbol 속성 구현  
    - [x]  number 속성 구현 
- [x] 출력 함수 구현 

### **🟢 학습 키워드**

- enum, rawValue
- CustomStringConvertible

### **🟢 고민과 해결**

- rank를 어떻게 구현해야할지 어려웠다. 처음에는 딕셔너리를 사용하셔 구현했는데, 현재 카드 정보를 출력할때는 키값을 얻어와야해서 결론적으로 속성을 하나 더 만들어야 했기때문에 좋은 방법이 아니라고 생각이들었다. 
그리고 rank의 값은 일관성이 있기 때문에, enum으로 구현하는것이 더 좋다고 판단했다.

2022-02-22 13:34 UTC, godrm requested changes
다음 피드백을 확인해보고 description 부분을 개선해서 다시 push해보세요

2022-02-22 13:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +    enum rank: Int, CustomStringConvertible {
범위가 한정적인 경우에 enum으로 잘 선언하셨습니다. 
다만 타입 이름은 대문자로 시작하도록 작성하세요

2022-02-22 13:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +    }
symbol 타입도 CustomStringConvertible 프로토콜을 지정해보세요. 
rawValue 그대로 출력할 지 아닐지는 여기서 판단하는 게 좋습니다

2022-02-22 13:34 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            let card = UIImageView(frame: CGRect(x: cardXPosition , y: 70, width: screenWidth/7.0 - gap, height: (screenWidth/7.0 - gap) * 1.25))
아직 `7`과 `7.0`이 하드코딩 되어 있네요. 개수라는 것도 명시해주는 게 좋습니다.
항상 값은 코드로 표현하려고 노력하세요

2022-02-22 13:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +
중간에 줄 간격이 띄엄띄엄하네요. 의도가 있는게 아니라면 일관성있게 표현해보세요.

2022-02-22 13:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        return "\(self.symbol.rawValue)\(self.number.description)"
문자열을 만들때는 description을 붙이지 않아도 객체에 선언된 description을 참조하게 됩니다.

2022-02-22 15:54 UTC, asqw887 commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            let card = UIImageView(frame: CGRect(x: cardXPosition , y: 70, width: screenWidth/7.0 - gap, height: (screenWidth/7.0 - gap) * 1.25))
매개변수로 카드 개수를 받게해서 값을 코드로 표현되도록 바꿔보았습니다. 
7이아닌 다른 수를 넣었을때도 뷰가 잘 구현되는걸 확인했습니다. 
   ```swift
       func configureCard(numberOfCards: Int){
            ...
            let cardXPosition: CGFloat =  CGFloat(CGFloat(i) * (screenWidth/numberOfCards) + gap )
             ...
       }
   ```

2022-02-22 15:56 UTC, asqw887 commented on PokerGameApp/PokerGameApp/Card.swift
> +    }
♦️ 같은 특수문자가 보여줄때만 필요하니까 굳이 rawValue로 설정할 필요가 없는거였군요..!
피드백 수용해서 코드 수정했습니다.

2022-02-22 15:56 UTC, asqw887 commented
피드백 보내주신 부분 개선해서 push 했습니다.

2022-02-23 02:18 UTC, godrm approved these changes
다음 단계 하기전에 description 부분을 개선해보세요

2022-02-23 02:18 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        return "\(self.symbol.rawValue)\(self.number)"
많이 깔끔해졌네요
문자열을 만들때 description을 제공하면 여기서 rawValue에 접근하지 않고 description 값을 가져오게 됩니다. 그걸 사용해보세요

2022-02-23 02:18 UTC, merged