[Pigbag] Step02 - 효율적인 데이터 구조 설계 하기
codesquad-members-2022/swift-pokergame pull request #42
Opened 2022-02-22 12:17 UTC by P-SeoB

* 작업 목록
 - [X] 스위프트에서 성능에 영향을 미치는 세가지 요소 인지하기
 - [ ] 성능에 영향을 끼치는 요소를 생각하며 데이터 구조짜보기
 - [X] 데이터를 처리하는 코드와 출력하는 코드 구분해보기

- - -

* 학습 키워드 : Dynamic, Static, value Type, ReferenceType, Existential Container

* 고민과 해결
   * 추천해주신 유용하님의 스위프트 성능이해하기를 학습하던 중 모르는 단어가 많아서 시간이 많이 걸렸습니다.
   학습한 내용을 가지고 코드에 적용을 해보려 헀지만 아직까지 어떤 방식으로 구조를 짜야 할지 확신이 잘 서지 않았습니다
   그래도 그 중 final과 private단어를 사용하여 Static Dispatch방식으로 강제하면 컴파일 성능이 좋아지지 않을까 하고 사용해 보았습니다.

   - Rank enum값을 정의할때 case를 1부터 13까지 나열하는 것이 코드를 늘어지게 한다고 생각이 들었습니다.
     그래서, Case별로 rawValue를 넣는 방법보다 카드의 숫자 별 Case를 두개로 나누고 처리를 하였습니다.
     하지만 오히려 1부터 13까지 나열할때보다  가독성이 떨어지고  CaseIterable프로토콜을 준수 하지 못하기에 allcases라는 프로퍼티를 새로만들어 주어야 한다는 번거로움이 생겼습니다. 숫자가 적당하면 반복작업을 하는것도 나쁘지 않겠다고 생각이 들었습니다.

- - -

* 질문거리 
   유용하님의 스위프트 성능 이해하기에서 Protocol type이 변수할당 part에서 Existential Container라는 개념이 나오는데요
  값이 3 word 이하인 경우 Value buffer에 저장되고 초과인 경우 Value buffer에 포인터처럼 주소를 담은 값을 추가해서 Heap공간에 할당하는 것으로 이해했습니다.
   ValueBuffer가 3 word로 정해진 이유가 있을까요? 
  제가 생각하기에는 1 word만큼의 값이 들어오면 2 word는 낭비가 되는 값이 되어버린다고 생각이 됩니다.
  그럴 바에는 Buffer를 애초에 1로 만들면 낭비되는 값을 줄일 수 있을것이라 생각이 되어서 질문을 올립니다.

2022-02-22 13:37 UTC, godrm commented
>   유용하님의 스위프트 성능 이해하기에서 Protocol type이 변수할당 part에서 Existential Container라는 개념이 나오는데요
>   3words 크기의 Value buffer와  메타 데이터로 이루어진 fix size로 이루어져있는 것으로 배웠습니다.
>   그래서 값이 3 word 이하인 경우 Value buffer에 담아 Stack에 저장되고, 초과인 경우 Value buffer에 포인터처럼 주소를 담은 값을 추가해서 Heap공간에 할당하는 것으로 이해했습니다.
>   ValueBuffer가 3 word로 정해진 이유가 있을까요?
>   제가 생각하기에는 1 word만큼의 값이 들어오면 2 word는 낭비가 되는 값이 되어버린다고 생각이 됩니다.
>   그럴 바에는 Buffer를 애초에 1로 만들면 낭비되는 값을 줄일 수 있을것이라 생각이 되어서 질문을 올립니다.

3word를 항상 잡아놓고 쓴다기 보다는 3word보다 큰 값인 경우는 heap을 쓰자. 정도로 이해하시면 됩니다
왜 그런지는 모르겠지만, 저라면 여러 데이터 구조를 보고 얼마나 차지하나 살펴볼꺼 같습니다.
그래서 아마도 상당수의 데이터 구조가 크기가 3개 이하이지 않았을까 싶네요 
엔지니어링은 기준을 정하고 가정하고 예측해서 구현하는 정도입니다. 
1word보다 큰 것을 모두 힙에 쓸꺼면 class와 다를게 없으니까요.

2022-02-22 13:38 UTC, godrm commented on PokerGame/PokerGame/Card.swift
> +}
이 타입은 뭘까요? 전혀 안쓰는 클래스인가요?

2022-02-22 13:48 UTC, godrm requested changes
CardInfo에 대해 피드백을 남겼습니다
Card와 어떤 차이가 있는지 살펴보시고 개선해서 Push 남겨주세요

2022-02-22 13:48 UTC, godrm commented on PokerGame/PokerGame/CardInfo.swift
> +    private var rank:String = Rank.randomRank
이 부분은 카드를 생성하기만 하면 랜덤으로 suit와 rank가 정해지는 걸까요?
그러면 원하는 카드를 만들려면 랜덤으로 정해질때까지 계속 생성해야 하는걸까요? 뭔가 좀 이상한데요

2022-02-22 13:48 UTC, godrm commented on PokerGame/PokerGame/CardInfo.swift
> +            Suit.allCases.randomElement()?.rawValue ?? "유효한 Suit가 없습니다."
Suit가 랜덤값을 바탕으로 인스턴스를 만들어 내는 것은 가능한 것 같은데 (그런걸 팩토리라고 부르죠), 문자열을 만드는 것은 왜일까요?
이 타입에서 해야 하는 역할인지 아닌지 구분이 잘 안됩니다.

2022-02-22 13:48 UTC, godrm commented on PokerGame/PokerGame/CardInfo.swift
> +        case alphabetType(Int)   //알파벳 A,J,Q,K
숫자와 알파벳으로 구분하는 시도는 나쁘지 않습니다
다만 이러면 모든 Rank타입을 사용하는 곳에서 값을 binding해서 꺼내야 하기 때문에 오히려 불편할 수도 있습니다
이렇게 생각해보면 어떨까요? 숫자를 비교하는 경우가 많을까요? 숫자인지/문자인지 구분하는 경우가 많을까요?

2022-02-22 13:48 UTC, godrm commented on PokerGame/PokerGame/CardInfo.swift
> +            return ranks
아.. CaseLiterable를 채택하기 보다 이렇게 코딩하는 게 더 효율적이라고 생각한건가요?
만약에 Rank에 종류가 하나 더 추가되면 여기 코드가 바뀌어야 하고 더 복잡해지지는 않을까요?

2022-02-22 13:48 UTC, godrm commented on PokerGame/PokerGame/CardInfo.swift
> +            default: return "유효하지 않은 숫자입니다 1~13사이의 숫자를 입력해주세요"
여기도 보면 케이스를 두 개로 구분했지만 각 number와 alphabet을 let binding 후에 비교하고 처리까지 하고 있습니다
Rank 같은 이런 타입은 엄청 자주 값으로 사용하는 가장 하위 타입이라서 심플하게 값만 가지고 최소의 동작을 처리하는 게 더 좋은 구조일 꺼 같습니다. 쉽게 표현할 수 있는 구조를 너무 복잡하게 표현하는 게 아닐까요? 
숫자를 나열하는 게 이것보다 작성하는 사람에게도 실행하는 컴퓨터에게도 효율적이지 않을까요?

2022-02-22 13:48 UTC, godrm commented on PokerGame/PokerGame/CardInfo.swift
> +    }
Rank 타입에 대해서 한 가지 더 짚어보고 싶은게 있네요
Rank값을 초기화 할 때 .numberType(0) 이나 .numberType(1234) 같은 값도 만들 수 있나요? 
그러면 카드는 그런 카드를 표현할 수 있게 되나요? 초기화 측면에서도 기준이 잘못된 부분이 있는 것 같습니다.

2022-02-23 00:28 UTC, P-SeoB commented on PokerGame/PokerGame/Card.swift
> +}
혹시나 나중에 카드를 뒤집거나 했을때 앞면인지 뒷면인지 여부 정도의 프로퍼티를 추가할 경우가 생기면 추가하려고 했습니다.

2022-02-23 00:31 UTC, P-SeoB commented on PokerGame/PokerGame/CardInfo.swift
> +    }
전체적으로 제가 초기화 방식을 잘못 생각한거 같습니다 다시 한번 생각해보겠습니다!

2022-02-23 00:33 UTC, P-SeoB commented on PokerGame/PokerGame/CardInfo.swift
> +    private var rank:String = Rank.randomRank
임의의 카드 하나를 뽑는다고 가정을 하고 생성을 한것 같습니다. 원하는 카드를 만드는 경우도 생각해보겠습니다.

2022-02-23 00:34 UTC, P-SeoB commented on PokerGame/PokerGame/CardInfo.swift
> +            default: return "유효하지 않은 숫자입니다 1~13사이의 숫자를 입력해주세요"
전체적으로 제가 너무 복잡하게 생각한것 같습니다 단순하게 표현할수 있는 것은 그렇게 하도록 노력해보겠습니다!

2022-02-23 00:39 UTC, P-SeoB commented
피드백 주신부분, 데이터구조 관련얘기 한번더 정리한후 push해보겠습니다. 
늦은밤에도 리뷰해주셔서 감사합니다!

2022-02-23 03:46 UTC, P-SeoB commented
> CardInfo에 대해 피드백을 남겼습니다 Card와 어떤 차이가 있는지 살펴보시고 개선해서 Push 남겨주세요

피드백 주신부분 수정하여 Push했습니다!

2022-02-23 05:43 UTC, godrm commented on PokerGame/PokerGame/Card.swift
> +        }
shape 자체가 문자열을 표현하는 거라면 그냥 description에 넣어도 되지 않을까요?
shape 속성을 계속 사용하는건가요? description과 차이가 없는 것 같습니다

2022-02-23 05:43 UTC, merged

2022-02-23 05:59 UTC, P-SeoB commented on PokerGame/PokerGame/Card.swift
> +        }
아.. 중복되는 부분이 있는것 같습니다. Shape가 하는 일을 description으로 옮긴후 다음 PR에 추가하겠습니다. 감사합니다!