[shingha] 코드리뷰 후 수정입니다!
codesquad-members-2022/swift-pokergame pull request #48
Opened 2022-02-23 06:26 UTC by shingha1124

## 작업내용

- [x] 상수로 지정한 값들 사용용도에 맞는 위치로 이동
- [x] CardDeck의 CustomStringConvertible 수정
- [x] 닉네임을 랜덤으로 뽑을 시 5자 이상 넘어가는 이름 필터링
- [x] 상수에 따로 연산을 하지 않고 사용 할 수 있도록 코드 개선
- [x] PokerPlayers클래스구현, 플레이어들 관리
- [x] 배열에 직접 접근하지 않고 처리해보기
- [x] StackView의 상속을 받은 카드뷰와 옵션뷰를 UIView를 이용하여 구현하기

2022-02-23 07:07 UTC, godrm requested changes
딜러 관련 부분을 개선해보면 좋겠습니다
카드를 전달하는 역할 요구사항이 빠진거 같아요

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +        static let defaultCount = 2
상수를 모아놓는 것도 좋습니다. 이렇게 static으로 선언한다면 enum 이나 struct 나 class도 가능할꺼 같은데 enum으로 한 이유가 있나요?

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +    public private(set) var players = [Player]()
Players 배열을 가지고 있지만 private으로만 처리하도록 바꿔보세요. 
대신 PokerPlayers에서 메소드를 제공해주도록 개선해보세요

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +    public private(set) var dealer = Player(name: "Dealer")
dealer를 별도로 주지 않고 player를 생성할 때 같이 생성해도 되지 않을까 싶다고 쓰려고 보니
아래에서 또 dealer를 생성해주네요. 두 번 생성하는 게 의도한걸까요? 
Dealer를 name으로 구분하지 않고 별도 타입으로 만드는 건 고려해보셨나요?

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +                           "jed", "beck", "eddy", "selina", "pigBag"].filter { $0.count <= 5}
사실 이렇게 filter할꺼면 아예 배열에 안 넣어도 되는거겠죠? 
이름을 여기서 결정하는 게 좋은 구조일까요?

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
>              }
(저는 약간 상상력을 동원해서 실제 카드 게임하는 것처럼) 요구사항에 있는 것처럼 딜러가 덱에서 카드를 나눠주는 동작을 담당해야 하는 역할이라고 생각하는 데 어떻게 생각하시나요?

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
> +            case .fiveCard: return 5
기존에 Int로 rawValue로 숫자를 지정해준 것과 어떤 차이가 있나요?

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Present/View/PlayerCardView.swift
>          fatalError("init(coder:) has not been implemented")
fatalError는 앱이 멈추는 코드라서 가급적 지양하세요.
이렇게 되어 있는 이유는 이 자리를 꼭 구현하라는 의미입니다. 이대로 두지 말라는 의미에요
init() 생성자는 어떤 생성자로 호출해서 생성하더라도 동일하게 초기화가 되야 한다는 사실을 꼭 기억하세요

2022-02-23 07:07 UTC, godrm commented on PokerGame/PokerGame/Sources/Present/View/PokerOptionView.swift
> +                pokerGame.action.inputPokerType(index == 0 ?.sevenCard : .fiveCard)
여기 들여쓰기 단계가 꽤 깊어졌는데, 복잡해 보이고 썩 좋아보이지 않네요. 
이렇게 들여쓰기가 깊어지는 코드가 있다는 것은 역할 분담이 안되고, 여기에서 모든것을 처리하고 있는 구조라는 의미기도 합니다
상위 모듈이 할 일과 하위 모듈이 할 일을 상위에서 모두다 하고 있지는 않나 항상 반문해보세요

2022-02-23 07:08 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
>              }
아 이부분을 놓치고 있었습니다!! 
수정해보겠습니다~!!

2022-02-23 07:14 UTC, shingha1124 commented
딜러가 카드를 나눠준다는 큰 구현사항을 빠트려서 
뭔가 정리가 안됬던것 같습니다!! 
딜러와 플레이어의 구분점을 찾았으니.. 구현해보고 푸쉬하겠습니다!

2022-02-23 07:24 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +        static let defaultCount = 2
스위프트를 처음 배울때 다른분들의 코드를 보면서 enum 안에 상수를 넣어 사용하고 있었습니다
방금 검색해보니 
1. 뜻하지 않는 초기화를 막을 수 있고
2. 순수히 namespace 로서만 작동
이러한 장점이 있다고 합니다!

2022-02-23 09:13 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +    public private(set) var players = [Player]()
private로 숨기고, 필요한 함수를 제작하여 값을 가져갈 수 있도록 수정했습니다.

2022-02-23 09:40 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +    public private(set) var dealer = Player(name: "Dealer")
pokerPlayer, dealer로 구분하여 동작하도록 구현하였습니다!

2022-02-23 09:41 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayers.swift
> +                           "jed", "beck", "eddy", "selina", "pigBag"].filter { $0.count <= 5}
뒤의 필터처리부분을 빼고 다른방법으로 구현하였습니다.

2022-02-23 09:42 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
> +            case .fiveCard: return 5
동작의 차이는 없지만 가독성에서 차이가 있다고 생각합니다
pokerType.rawValue 를 사용할 경우 어떤값을 주는지 보는사람 입장에서는 모를것 같습니다.

그래서 cardCount라는 프로퍼티를 만들어, 각각 타입에 필요한 카드갯수를 리턴하도록 했습니다.

2022-02-23 09:52 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Present/View/PlayerCardView.swift
>          fatalError("init(coder:) has not been implemented")
넵! 
init에서 처리하던 내용을 Initialize 함수를 만들어, 위의 두 init 함수에서 호출하도록 구현해보았는데
괜찮은 방법인지는 모르겠습니다.

2022-02-23 09:55 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Present/View/PokerOptionView.swift
> +                pokerGame.action.inputPokerType(index == 0 ?.sevenCard : .fiveCard)
중첩되는 부분은 함수로 따로 빼고, 조금 더 보기 편하게 수정해보았습니다.

2022-02-24 00:15 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/PokerPlayer.swift
> +}
이렇게 아무런 구현부분이 없는 클래스가 있다면 그냥 Player를 사용해도 된다는 의미기도 합니다.

2022-02-24 00:17 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
> +        if dealer.cardCount < (pokerPlayers.count + 1) * pokerType.cardCount {
저라면 이런 비교식도 여기서 구현하기 보다는 cardDeck 혹은 dealer에 메소드로 구현할 것 같습니다 
하위 타입의 값을 가져와서 상위에서 처리하려고 하기 보다는, 하위 타입에게 물어봐서 결과만 처리하는 방식이 좋습니다

2022-02-24 00:17 UTC, merged