[shingha] step-6 승자표시하기 작업 진행중
codesquad-members-2022/swift-pokergame pull request #66
Opened 2022-02-24 07:12 UTC by shingha1124

## 작업목록

- [x] 점수 계산 로직 추가
  - [x] Score 클래스 제작
- [x] 점수 계산 XCTest코드 작성
  - [x] 원페어, 투페어, 트리플, 스트레이트, 포카드 테스트 후 확인
  - [ ] 전체 게임 플로우 테스트 후 결과 확인하기
- [ ] 승자 UI 화면 구성

## 고민과해결

* 점수계산하기!
  * 플레이어는 PokerPlayers클래스 안에서 관리
  * 딜러는 PokerGame에서 따로 관리
  * 점수계산을 하려고 보니... 플레이어들은 PokerPlayers, 딜러는 PokerGame...
  * PokerPlayers여기서 한번 계산해서 높은점수를 받아오고,,, 나와서 딜러랑 또 비교??
  * 생각해보니 딜러도 플레이어라고 판단.. PokerPlayers에 딜러도 넣음
    * 플레이어와 동일한 동작만 같이 처리됨, 카드 받고, 점수계산하고, 게임 끝나면 카드 지우고,,
  * PokerPlayers로 딜러도 넣어보니, 카드받고 UI를 갱신시켜주는 바인딩처리도
    모두 같이 사용할수 있게되어 딜러만을 위했던 바인딩함수를 삭제
  * 위처럼 처리하고 PokerPlayers에서 점수계산을 하고 한명의 우승자만 선출 할 수 있게됨

2022-02-24 07:34 UTC, godrm requested changes
다음 내용을 확인해서, 수업시간에 언급했던 것처럼 객체끼리 비교하도록 개선해보세요

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Card/Card.swift
> +        }
Equatable을 채택했는 데 구현한 것은 > 비교하는 Comparable 관련 이네요. 어떻게 된걸까요?

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/Dealer.swift
> +    func hasRemainCardCount(stud: PokerGame.Stud, playerCount: Int) -> Bool {
혹시 playerCount는 타입으로 선언하지 않았나요? Int 보다 더 적은 범위를 갖으니 타입을 선언해보세요

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +        cards.sort(by: {$0.number.rawValue < $1.number.rawValue})
여기 sort는 카드 배열에 있는 카드들을 비교하는 거니까 Card.number 속성을 가져오지 않고 Card 끼리 비교하도록 개선해보세요
Card도 속성을 모두 private으로 만들 수 있을겁니다.

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
>              }
이 부분도 pokerPlayers 속성을 가져오고, pokerPlayers에게 따로 여러번 요청하는 게 아니라 
Game 은 Players에게 한꺼번에 요청하고, Players가 반복하는 구조가 가능할까요?

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
> +//        }
사용하지 않는 코드는 과감하게 지우셔도 됩니다

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerPlayers.swift
> +        print(score)
여기도 player.score를 가져와서 비교하는 게 아니라 player 객체끼리 비교하도록 개선해보세요

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Score/Score.swift
> +        //숫자 별로 갯수를 정리
Score에 Player를 넘겨서 계산하는 게 아니라, 
Player 내부에 카드가 있으니 카드를 Score에 넘겨서 계산해서 결과를 Player 내부에 두는 구조는 어떨까요?

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Present/PokerBoardViewController.swift
>      }
타입과 역할이 정리되니까 뷰를 처리하는 코드도 더 심플해지는군요

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Present/View/PlayerButton.swift
> +    }
모든 객체의 생성자는 같은 역할을 해야 합니다. 
init()만 보면 서로 다른 역할을 하는 것 같습니다. 
특히 UIView 하위 클래스들은 두 가지 지정 생성자가 있습니다. 
init(frame:) 과 init?(coder:)입니다. 이 두 가지로 생성되는 것을 보장하고, 추가적으로 생성할 때도 이 생성자를 활용하는 게 좋습니다.

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGame/Sources/Present/View/PokerStudButton.swift
> +        self.pokerStud = pokerStud
이 버튼은 상속해서 만든 이유를 모르겠습니다. 
버튼을 누르면 pokerStud가 바뀌는 것도 아니고, 세부적인 동작이 다른게 없어서 UIButton을 쓰는 것과 어떤 차이가 있는지 모르겠습니다.

2022-02-24 07:34 UTC, godrm commented on PokerGame/PokerGameTests/PokerGameTests.swift
> +                print("\($0) -- 점수없음")
test함수에서도 print()를 하기보다는 값을 확인하는 것도 Assert 구문으로 확인하는게 좋습니다.

2022-02-24 08:10 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
>              }
앗 이부분은 리뷰를 놓첬었네요!!
pokerPlayers 내부에 카드를 분배하는 코드를 넣고, @escaping를 사용해 핸들러를 추가하여 
뷰를 갱신 할 수 있도록 수정했습니다

2022-02-24 08:17 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Card/Card.swift
> +        }
처음에 ==을 사용하기 위해 구글링을 해보니 Equatable 사용하는 방법을 찾았었는데
> 가 필요해서 교체하고, Equatable를 지우지 않았습니다 
Equatable, Comparable을 조금더 찾아보고 적용해 보겠습니다!

2022-02-24 08:21 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +        cards.sort(by: {$0.number.rawValue < $1.number.rawValue})
sort 함수를 수정하고 줄여보니, sort함수 뒤에 인자값을 따로 넣지 않아도 처리되는것을 확인했습니다
cards를 private로 변경해보니 sort가 아닌 sorted함수가 필요해서 리턴을 해주는 sorted로 변경했습니다.

2022-02-24 08:22 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/PokerGame.swift
> +//        }
앗 작업하다가 남은 코드가 있었네요 
더 세세히 확인하겠습니다

2022-02-24 08:23 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/PokerPlayers.swift
> +        print(score)
이부분을 만들면서도 lhs.1.rule등 다른사람들이 보기 힘들겠다?라고 생각은 들었습니다
객체비교로 진행할 수 있도록 개선해보겠습니다.

2022-02-24 09:27 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Score/Score.swift
> +        //숫자 별로 갯수를 정리
이 부분도 계산하는 위치를 어디다 둘까 고민하다가 우선 여기에다가 두었습니다
플레이어로 위치 이동하겠습니다

2022-02-24 11:43 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Present/View/PlayerButton.swift
> +    }
넵 다음에 다른 클래스를 생성할때 주의하겠습니다
이 클래스는 삭제될 예정입니다!

2022-02-24 11:44 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Present/View/PokerStudButton.swift
> +        self.pokerStud = pokerStud
버튼에 값을주고 그 값을 참조해보려고 했습니다.
조금 더 파보니 다른방법을 찾은것 같아 이 클래스는 삭제 예정입니다!

2022-02-24 13:13 UTC, shingha1124 commented on PokerGame/PokerGameTests/PokerGameTests.swift
> +                print("\($0) -- 점수없음")
비지니스 실행 로직에서 테스트코드를 어떻게 넣어야 하는지 고민하다가
예제로 사용할 카드를 만들고, 샘플 플레이어를 만들고, 플레이어를 비지니스로직에 넣어
계산을 진행하고, 승자를 선출하는 테스트케이스를 만들었습니다

2022-02-24 13:15 UTC, shingha1124 commented
피드백 주신부분 수정해 보았습니다~
XCTest를 다뤄보니 점점 왜 사용하는지 알것 같습니다~~
리뷰감사합니다

2022-02-25 01:20 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Card/Card.swift
> +        lhs.number < rhs.number
Card 입장에서 pattern은 비교 대상이 아니었나보네요. 내부 속성을 비교할 대상으로 결정하는 게 중요한 포인트입니다

2022-02-25 01:21 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +    func scoreCalculation() {
score가 `점수를 얻다`는 동사가 있어서 가능은 한데 Calculation과 중복되는 느낌도 있네요

2022-02-25 01:22 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +        }
이 정도는 `,`로 이어서 표현해도 좋겠네요

2022-02-25 01:23 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +            }
Score 타입이 있지 않았나요? 아.. Score가 점수를 표현하는 거군요
그러면 Player와 별개로 점수만 계산하는 로직을 가지는 하위 타입이 있는 것도 좋았을 것 같습니다.

2022-02-25 01:24 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/PokerPlayers.swift
> +            (0..<count.value).forEach { index in
pokerStud.cardCount 값을 가져와서 forEach 루프를 도는 것말고
pokerStud에 클로저를 넘기고 내부 값만큼 탐색하도록 만드는 것도 상상해보세요

2022-02-25 01:25 UTC, godrm commented on PokerGame/PokerGameTests/PokerGameTests.swift
> +        }
경우의 수를 다루는 것도 좋은데, 테스트 함수마다 있거나 작게 분리하는 것도 좋습니다.
이런 테스트 코드 자체가 길어지면, 버그가 생길 수 있는 경우도 많아질 수도 있습니다.

2022-02-25 01:26 UTC, godrm commented on PokerGame/PokerGameTests/PokerGameTests.swift
> +        print("-------------------------------")
테스트 함수 내에서도 print말고 Assert로 값을 확인하는 게 좋습니다. 
어차피 테스트 함수는 사람이 하는 게 아니고 기계가 대신하거든요

2022-02-25 01:26 UTC, godrm commented
수고하셨습니다. 처음 설계했던 아이디어에서 지금 구현한 내용까지 흐름과 변화를 정리해보시면 좋겠습니다.

2022-02-25 01:26 UTC, merged

2022-02-25 01:29 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Card/Card.swift
> +        lhs.number < rhs.number
넵 우선 숫자만 비교하고 있었고, 문양등급 순위 파악해서 적용했습니다

2022-02-25 01:41 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/PokerPlayers.swift
> +            (0..<count.value).forEach { index in
stud에 카드배분을 위한 함수를 제작하고, 클로저로 처리할 수 있도록 수정했습니다.

2022-02-25 01:41 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +        }
이 부분 코드 정리했습니다

2022-02-25 02:01 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/Player/Player.swift
> +            }
점수계산 하는 로직을 Score로 옮기고, 플레이어를 관리하는 PokerPlayers클래스에서 
플레이어들의 점수를 뽑아 승자를 가리도록 수정했습니다.