[shingha] step2 - 카드 데이터 & 카드 덱 구현
codesquad-members-2022/swift-pokergame pull request #9
Opened 2022-02-21 09:06 UTC by shingha1124

## 작업목록

- [x] 카드데이터를 관리할 Struct 제작
- [x] 카드데이터를 문자열을 변환하는 함수 제작
  - [x] 단위테스트
    - [x] CardData 객체 인스턴스 & 출력 테스트
- [x] CardDeck 클래스 구현
- [x] CardDeck 필요 함수 구현
  - [x] 단위테스트
    - [x] CardDeck 인스턴스 테스트
    - [x] CardDeck Shuffle() 테스트
    - [x] CardDeck RemoveOne() 테스트
    - [x] CardDeck Reset() 테스트

## 학습 키워드

* 단위테스트, struct, class

## 고민과 해결

* **단위테스트**
  * 단위테스트가 어떤식으로, 어떻게 하는것인지 모르고 있었음( 채용공고에 보면 단위테스트를 보는 회사도 많았는데...)
  * 단위테스트가 어떤것인지 궁굼해하고 있던 중 오늘 수업중에 나옴
  * 기존 테스트는 코드짜고, 빌드돌리고, 시뮬레이터에서 확인
  * 오늘 수업을 듣고 단위테스트를 적용, 내가 만든 코드를 간단하게 테스트 해볼수 있었음!
  * 아직 기초만 사용하는 것 같지만, 좀더 알아보고 더 나은 단위 테스트를 진행해 보아야겠음

2022-02-21 12:29 UTC, godrm requested changes
다음 내용 중에서 CardData와 CardDeck 부분은 수정해서 다시 보내보세요

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +        "\(pattern.rawValue)\(numberToString())"
Swift에서는 toString 대신에 description을 사용합니다. CustomStringConvertible 프로토콜을 살펴보세요

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +    let number: Int
CardPattern이라는 enum을 선언했는데 number는 Int로 그대로 사용하네요
비슷하게 선언할 수 있지 않을까요?

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +            return String(number)
number를 처리하는 타입도 enum으로 선언해보시고 여기 메소드를 CustomStringConvertible을 적용해보세요

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        deck = newDeck
이런 로직을 구현할 때는 메소드 하나씩 단위 테스트를 할 수 있는가
다시 말하면 이 함수는 어떻게 테스트할 수 있는가를 고민해봐야 합니다
이 함수는 어떻게 테스트할 수 있을까요? 테스트하기 좋은 함수는 어떤 구조를 가지게 될까요? 

한 가지 더, shuffle()함수가 removeOne()함수에 의존하는 데 섞기 위해서 제거하는 기능이 꼭 있어야 할까요?
섞기만 하고 하나를 뽑는 것은 서로 별개로 구현할 수 있지 않을까요?

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        return deck.remove(at: randomIndex)
이 함수는 어떻게 테스트 할 수 있을까요? 랜덤값은 테스트할 수 있을까요?

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        }
allCases로 접근한 경우에 꼭 flatMap()으로 접근해야 할까요? 다른 방법은 뭐가 있을까요?

2022-02-21 12:29 UTC, godrm commented on PokerGame/PokerGameTests/PokerGameTests.swift
> +        print("남은 카드 갯수: \(cardDeck.count)")
테스트 함수에서도 print()를 할 필요는 없고, 값을 확인하면 됩니다. 
값을 확인할 때 사용하는 단언 Assert 함수들을 찾아보세요
XCTAssertEqual() 부터 사용해보시기 바랍니다.

2022-02-21 12:42 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +        "\(pattern.rawValue)\(numberToString())"
CustomStringConvertible 프로토콜은 처음 접해본 용어네요!
적용해 보겠습니다.

2022-02-21 12:59 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +    let number: Int
int로 그대로 놔뒀던 이유는 추후 카드 게임 제작시(포커룰을 잘 몰라서) 숫자로 연산하는 경우가 있을까 하여 
변경하지 않았습니다 ㅎㅎ
enum으로 선언해 수정했습니다.

2022-02-21 13:00 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +            return String(number)
enum 으로 변경 후 CustomStringConvertible을 사용하여 적용했습니다.

2022-02-21 13:10 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        deck = newDeck
기존 값 하나를 삭제하고 다시 넣는 형식의 셔플은 제거하고 
Knuth Shuffle의 셔플을 참고하여 스왑형식으 셔플로 변경하였습니다.
랜덤형식이 들어가는 함수의 경우 테스트 방법을 한번 찾아보겠습니다.

2022-02-21 13:35 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        return deck.remove(at: randomIndex)
이후 작업에 테스트를 해보았습니다.
덱 안에 있는 카드를 모두 뽑아보는 형태로 테스트 했습니다. 
카드를 뽑으면서 뽑은 카드는 따로 저장해 놓고, 중복된 카드를 뽑았는지? 카운트는 잘 깍였는지, 
for문을 전부 처리했을때 카운트가 0인지 체크합니다!

2022-02-21 13:41 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        }
flatMap을 사용한 이유는 카드데이터의 초기화가 init?로 작업해 두었습니다. 1~13을 벗어나는 숫자가 오는경우 생성하지 못하게 막아두었었습니다. 
그냥 for문으로 처리를 할지, reduce를 사용해볼지 고민하다가 reduce를 사용하여 처리해 보았습니다!

2022-02-21 13:42 UTC, shingha1124 commented on PokerGame/PokerGameTests/PokerGameTests.swift
> +        print("남은 카드 갯수: \(cardDeck.count)")
PR올리고 난 후 다음스텝 작업에서 XCTAssertEqual, XCTAssertTrue, XCTAssertFalse등을 사용해 보았습니다! 
다음 PR때 수정해서 올리겠습니다!

2022-02-21 13:46 UTC, shingha1124 commented
코드리뷰 해주신 부분 수정하였습니다!!
몰랐던것들을 몇개 알았습니다 ㅎㅎ 감사합니다!

2022-02-21 23:24 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +        }
number를 CardNumber 타입으로 사용하는 거라면 생성자 매개변수도 CardNumber 타입이어도 되지 않을까요?

2022-02-21 23:25 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +        "\(pattern.rawValue)\(number)"
이렇게 생각해보세요. 
CustomStringConvertible 프로토콜에서도 `pattern.rawValue` 직접 rawValue로 표현하지말고
`\(number)`처럼 `\(pattern)`으로 호출하면, pattern 타입이 자신의 표현 방식을 결정할 수 있지 않을까요?

2022-02-21 23:26 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        }
shuffle()과 shuffled() 처럼 가변 혹은 불변 메소드를 모두 고려해보면 좋습니다.

2022-02-21 23:27 UTC, godrm commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        }
여기도 1...13 말고 CardNumber.allCases를 쓰면 어떨까요?

2022-02-21 23:28 UTC, godrm commented
나머지들은 다음 단계하면서 개선해보세요

2022-02-21 23:28 UTC, merged

2022-02-22 00:32 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardDeck.swift
> +        }
넵넵 enum형으로 변경하고, 숫자가 굳이 필요가 없었네요. 
CardData.Init?으로 만들 이유도 사라졌습니다!

2022-02-22 00:34 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +        }
number를 cardnumber 타입으로 변경하여 처리하였습니다

2022-02-22 00:35 UTC, shingha1124 commented on PokerGame/PokerGame/Sources/Model/CardData.swift
> +        "\(pattern.rawValue)\(number)"
카드패턴도 CustomStringConvertible을 사용하여 수정하였습니다!