[Selina] Step2-4 - 게임로직 구현하기
codesquad-members-2022/swift-pokergame pull request #90
Opened 2022-02-25 14:08 UTC by ios-h

## 💻 작업 목록

- [x] Step2-3의 PR 리뷰 반영
- [x] XCTest 적용
- [X] PokerGame 객체 생성
- [X] 딜러 구현
- [X] 참가자 구현
- [X] Step2-4 README.md 작성

## 📱 실행 화면

![스크린샷 2022-02-25 오후 10 43 53](https://user-images.githubusercontent.com/95578975/155725923-7dd060b6-2009-4d0d-a051-75c44bcc6a9b.png)

## 🤔 고민과 해결

### 1️⃣ XCTest 코드 작성하기

- setUpWithError() : 테스트 메소드가 실행되기 전 모든 상태를 reset (초기화 코드)
- tearDownWithError() - 테스트 동작이 끝난 후 모든 상태를 clean up (해체 코드)

### 2️⃣ 'CardGame' initializer is inaccessible due to 'private' protection level

- 문제 발생 이유: 구조체의 내부 프로퍼티를 private으로 설정하고 cardCount의 초기값을 지정해주지 않아서 발생한 문제.
- 해결 방법: cardCount의 초기값을 0으로 설정
- 접근 제어자 관련 학습
- 최종적으로 삭제된 코드입니다.

### 3️⃣ instance member cannot be used on instance of nested type swift

Dealer 구조체 내의 distributeCard(to:)에서 cardStud를 사용하려고 하니 위의 메시지와 같은 오류가 났습니다.
(인스턴스 멤버는 Swift의 중첩된 타입에서 인스턴스로 사용될 수 없다는 것)

- 문제 발생 이유 [자료](https://forums.swift.org/t/is-it-ok-that-i-cannot-instantiate/43389/2)

  Nested types in Swift as of now serve only namespasing purposes; beyond that, they are not "linked" to the containing type and aren't aware of any of its properties or methods. 

- 해결 방법

  cardStud를 private에서 static으로 변경하였습니다. static은 프로퍼티를 인스턴스화하지 않고 하나만 존재하도록 하기 위해 사용되는데, 최종적으로 cardStud도 distributeCard(to:) 메소드 내에서 삭제되었습니다.

## ❓ 느낀 점

구현하면서 부족하다고 생각되었던 부분이 많아 추가적으로 공부를 더 할 예정이고, Struct, Class의 특징과 차이점에 대해서 다시 한번 제대로 정리를 해봐야겠다고 생각했습니다. 접근제어자와 프로퍼티에 대해서도 학습을 더 할 예정입니다.

## 💡 학습 키워드

- Struct
- Class
- static
- 접근 제어자 (Access control)

2022-02-27 12:22 UTC, godrm requested changes
다음 피드백을 확인해서 개선해보세요.
개선하고 다시 push해도 될 것 같습니다.

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        return lhs.description == rhs.description
뭔가 값을 비교하거나 처리하는 데 description 값은 사용하지 마세요. 문자열 비교가 성능이 나쁘기도 하지만, description은 데이터가 아니라 디버깅 정보 같은 겁니다. 
대신 어떤 속성을 비교하는 게 좋을까요?

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    var players = [Player]() // run 하면 players를 추가해줍니다.
속성들은 private을 늘 우선적으로 고려하세요

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    static var cardStud: Int = Stud.five.rawValue // default는 5카드 스터드
이 속성들은 왜 static var로 되어 있나요? 게임 인스턴스와 상관없는 건가요?

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        print("포커게임을 종료합니다👋")
print 호출은 자제하세요. 흐름에 따라서 앱에서 사용자에게 알려줘야 하는거지, print는 좋은 습관이 아닙니다.

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        PokerGame.totalCards.shuffle()
여기 있는 흐름들이 필요한 것은 알겠는데, run()에서 다 처리하지 말고 나눠서 처리하도록 하는 것도 좋습니다.

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        }
다른 타입이면 별도 파일로 분리해서 선언하는 게 좋습니다. 
Game.Dealer로 꼭 내부 타입이어야 하는 가도 고민해보세요

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        mutating func distributeCard(to players: inout [Player]) -> Int {
`inout [Player]` inout은 사용하지 않는 것을 권장합니다. 
딜러에게 참자가를 다 넘겨주는 게 아니라, 딜러에게 카드를 받아서 전달하도록 하는 방법도 있겠네요.

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +                    return -1
에러를 -1로 표현하는 것도 좋은 습관은 아닙니다. throw를 처리하는 것도 고민해보세요

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        var cards = [Card]()
Player는 전혀 구현 내용이 없는 건가요? 이런 타입이라면 선언할 필요가 없는 것 아닐까요? 
속성이 있으면 그것을 처리하는 메소드가 있어야 타입을 선언하는 의미가 있습니다.

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +
프로토콜도 어딘가 관련있는 타입들과 같은 파일에 두거나, 별개 파일로 처리하는 게 좋습니다

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameAppTests/PokerGameAppTests.swift
> +        sut2.run()
테스트를 할 때는 실행만 하는게 아니라, 입력에 따라 다르게 동작하는 경우를 확인하는 Assert가 있어야 합니다.

2022-02-27 12:22 UTC, godrm commented on PokerGameApp/PokerGameAppTests/PokerGameAppTests.swift
> +    var sut2: PokerGame!
XCTestCase 하위 타입은 속성으로 선언하더라도 setUp()과 tearDown()을 사용하는 게 좋습니다.
그렇지 않으면 테스트 함수들이 독립적으로 실행하지 못할 수 있습니다

2022-02-28 08:00 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        print("포커게임을 종료합니다👋")
print문 제거하고 breakpoint로 로그 메시지 출력하도록 수정하였습니다!

2022-02-28 08:34 UTC, ios-h commented on PokerGameApp/PokerGameApp/CardDeck.swift
> +        return lhs.description == rhs.description
Card에 Equatable 프로토콜을 채택하고 CardDeck에 있는 cards 속성을 비교하도록 변경하였습니다.

2022-02-28 12:24 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +
별도의 파일로 분리하였습니다.

2022-02-28 14:16 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    static var cardStud: Int = Stud.five.rawValue // default는 5카드 스터드
게임 인스턴스와 상관이 있어야하는건데 잘못 작성하였습니다. private var로 모두 수정하였습니다.

2022-02-28 14:16 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    var players = [Player]() // run 하면 players를 추가해줍니다.
private var로 수정하였습니다

2022-02-28 14:17 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        }
Dealer, Player 모두 별도의 파일로 분리하였습니다!

2022-02-28 14:19 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        mutating func distributeCard(to players: inout [Player]) -> Int {
Participant 프로토콜을 다음과 같이 수정하였습니다.
```swift
protocol Participant {
    var cards: [Card] { get set }
    
    mutating func receive(card: Card)
}
```

Dealer에는 카드를 빼주는 역할인 `remove(card:)`와 딜러 자신이 카드를 받기 위한 `receive(card:)`를 추가했고, Player에는 카드를 받는 `receive(card:)`  메소드를 추가하였습니다.

2022-02-28 14:20 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        var cards = [Card]()
Player를 별도의 파일로 분리하고 receive 메소드를 추가하였습니다.

```swift
struct Player: Participant, CustomStringConvertible {
    var description: String {
        return "👤User(\(name)): \(self.cards)"
    }
    
    var name: String
    var cards = [Card]()
    
    
    // 카드를 받습니다.
    mutating func receive(card: Card) {
        cards.append(card)
    }
}
```

2022-02-28 18:17 UTC, ios-h commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +                    return -1
PokerGameError을 추가하여 throw로 처리하였습니다.

2022-02-28 19:14 UTC, ios-h commented
JK 리뷰 너무 감사합니다!
말씀해주신 것들 최대한 반영하려고 노력해보았는데 그래도 한참 부족하네요..
오늘 중으로 테스트 코드 수정해서 추가로 푸시하겠습니다..!

2022-03-01 03:31 UTC, ios-h commented
테스트 함수 수정하여 푸시하였습니다!

2022-03-01 08:21 UTC, godrm approved these changes
수고하셨습니다. 하위 타입과 구조를 나누는 연습을 계속하게 될 겁니다 
Game 같은 상위 타입에서 하위 타입의 값을 가져와서 계산하거나, 비교하거나, 확인하지 않는지 살펴보세요

2022-03-01 08:21 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +    var cards = [Card]()
여전히 private var로 되어 있지 않은 경우가 있네요

2022-03-01 08:21 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +        return (currentCard.removeOne(), currentCard)
딜러가 카드덱을 변경해야 한다면 다시 되돌려 주기 보다는 아예 속성으로 소유하는 것도 고려해보세요 
받아서 변경하고 리턴한다는 것 자체가 좀 어색합니다

2022-03-01 08:21 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +        cards.append(card)
이 정도 주석은 함수 이름만 봐도 유추할 수 있는 정보라서, 추가적인 정보가 아니라서 정보가 없는 불필요한 주석입니다
코드를 봐서 알 수 있는 내용보다는, 그것보다 더 상세한 정보를 추가하려고 노력해보세요

2022-03-01 08:21 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
> +    var cards: [Card] { get set }
차츰 이야기하겠지만, 프로토콜로 추상화를 시도할 때는 속성은 빼고 공통 메소드를 추상화하려고 노력해보세요

2022-03-01 08:21 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +                }
Players 타입을 만들면 이렇게 players 배열에 접근하는 코드들을 모두 하위 타입으로 옮길 수 있습니다. 
게임이 가장 상위 타입이기 때문에 여기서는 필요한 흐름들만 제어할 수 있도록 정리하는 게 좋습니다

2022-03-01 08:21 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    private mutating func getCard(of player: Player) throws -> [Card]? {
게임에 있는 모든 함수들이 mutating으로 계속 속성을 바꾸는 타입이라면 class로 만드는 게 낫지 않나 생각해보세요

2022-03-01 08:21 UTC, merged