[Kai] Step4 : 포커 게임 로직, XCTest 구현
codesquad-members-2022/swift-pokergame pull request #91
Opened 2022-02-25 18:16 UTC by TaeKyeongKim

## [작업 내용]
- [X]  포커 게임 로직 구현하기
- [X] XCTest를 위한 테스트 타깃을 추가한다
- [X] 테스트 코드에서 PokerGame 메소드를 호출해서 동작을 확인한다

## [학습 키워드] 
- XCTest
- 접근 제한자 
- Struct 
- Class 
- Enum 
- CustomStringConvertible

## [고민과 해결]
- [접근 제한자] Person 이란 상위 클래스에서 name 과 cards 프로 퍼티 둘다 private 으로 만들어 버리면 이 클래스를 상속받은 하위 클래스 들이 cards 에 접근을 할수가 없다 (카드를 받을때 필요함).

→ 상위 클래스에 cards 프로퍼티를 만들어주고 이에 관련 메소드 `getCard` 도 person 클래스에서 구현함. 

- [접근 제한자] PokerGame 의 메소드를 사용자(코드 작성자) 가 필요한 기능만 `public` 으로 지정해주니 `run()` 외 에 다른 함수들은 전부 `private` 접근제한자로 설정이 되어 버렸다. `XCTest` 에서 클래스 관련 메소드를 테스트 해봐야 하는데 각각의 메소드에 접근이 불가능 했다.

→ 외부에서 읽기만 가능하고 내부에서만 수정이 가능하도록 private (set) 설정.

- [readLine()] 문제의 요구사항중  “카드 개수나 참가자 인원에 대한 입력을 구현할 필요없다” 라는 의미를 이해할수 없었었다.

→ 사용자의 입력을 받는 readLine() 함수를 써서 구현하려고 했는데 playground, IOS 응용프로그램에서는 STDIN 을 쓸수 없다고 해서 뒤늦게 왜 입력을 구현할 필요가 없다는건지 이해를 했다.

2022-02-27 12:34 UTC, godrm requested changes
Dealer와 Player 부분은 좀 개선이 필요해보입니다 
다음 내용은 확인해보세요

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/CardDeck.swift
> +        self.cards = scratch.reversed()
reversed는 왜 한건가요? 주석이 코드를 그대로 보면 알 수 있는 내용보다는 왜 그렇게 했는지 부가적인 정보가 있어야 합니다

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +        super.init(name: PokerGame.Roster.Dealer.rawValue)
뭔지 모르겠지만, PokerGame.Roster.Dealer 가 case 값이면 이걸 그냥 쓰면 됩니다. rawValue를 직접 써야 한다면 enum 타입을 선언할 필요가 없는거죠

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +                    player.getCard(card)
`player.getCard(card)` 이 부분은 참가자한테 카드를 가져오는 것 같네요.
보통 get- 은 객체의 속성을 가져오는 함수니까 헷갈리는 것 같습니다.

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +                    throw PokerGame.Errors.InsufficientCard
여기 있는 값들이 전형적으로 하위 타입의 속성을 가져와서 처리하는 부분들입니다.
mode.rawValue, playerList 배열까지 여기서 다 가져와서 처리하고 있네요. 
PokerGame.GameMode는 게임의 모드니까 게임에서 접근하는 값이 맞는 것 같네요. 
모든 값을 딜러에게 다 주고 처리하라고 하는 구조도 좋은 구조는 아닙니다.

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Person.swift
> +        return "\(self.name) \(self.cards[..<cards.count])"
참고로 Array는 이미 CustomStringConvertible 프로토콜을 채택해서 description을 처리해줍니다.

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Player.swift
> +
class Player는 전혀 구현 내용이 없네요. 이렇게 속성도 메소드도 없는 타입은 그냥 Person을 쓰면 된다는 의미입니다

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/PokerGame.swift
> +        print("현재 게임 모드: \(self.gameMode.rawValue)카드 \n플레이어 수 : \(self.numberOfPlayers.rawValue)명 \n게임 실행 횟수 : \(self.numberOfSet)회")
print도 로직에 포함하지 말고 이런 값을 확인하려면 필요한 상황에서 값을 가져가는 게 좋습니다
앱에서는 전혀 호출할 경우가 없는 메소드네요

2022-02-27 12:34 UTC, godrm commented on PokerGameApp/포커게임Tests/_________Tests.swift
> +class ___FILEBASENAMEASIDENTIFIER___: XCTestCase {
이름이 왜 이렇게 되어 있는거죠?

2022-02-27 12:46 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/CardDeck.swift
> +        self.cards = scratch.reversed()
최적화된 Fisher-Yates Shuffle 에서 마지막에 배열 `scratch ` 의 순서를 뒤집는줄알았는데 제가 착각한것였네요..

2022-02-27 13:01 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +                    player.getCard(card)
플레이어가 카드를 받는다는 의미에서 `player.getCard()` 라고 작성한건데 메소드명이 정확하지않아 참가자한테 카드를 가져오는것같이 느껴지네요.  `player.recieveCard(card)` 로 변경 하였습니다.

2022-02-27 13:16 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +                    player.getCard(card)
플레이어가 카드를 받는다는 의미에서 player.getCard() 라고 작성한건데 메소드명이 정확하지않아 참가자한테 카드를 가져오는것같이 느껴지네요. player.recieveCard(card) 로 변경 하였습니다.

2022-02-27 13:40 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +        super.init(name: PokerGame.Roster.Dealer.rawValue)
넵

2022-02-27 14:59 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +                    throw PokerGame.Errors.InsufficientCard
딜러의 `dealCard()` 메소드를 아래와 같이 바꾸고 playerList 매개변수로 보내는것이 아닌, 게임에서 접근하여 playerList 를 순환 하는 방식으로 바꾸었습니다. 
이외의 어색한 변수명도 바꾸어 주었습니다. 

```swift
 func dealCard(to player:Person , from deck : Deck) throws {
        if let card = deck.removeOne() {
            player.recieveCard(card)
        }else{
            throw PokerGame.Errors.InsufficientCard
        }
    }
```

2022-02-27 15:00 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/Person.swift
> +        return "\(self.name) \(self.cards[..<cards.count])"
오.. 좋은 정보 감사합니다. 수정하였습니다.

2022-02-27 15:01 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/Player.swift
> +
넵 Player 클래스는 삭제 하였습니다.

2022-02-27 15:05 UTC, TaeKyeongKim commented on PokerGameApp/PokerGameApp/Models/PokerGame.swift
> +        print("현재 게임 모드: \(self.gameMode.rawValue)카드 \n플레이어 수 : \(self.numberOfPlayers.rawValue)명 \n게임 실행 횟수 : \(self.numberOfSet)회")
각각의 변수 값을 불러 올수 있는 함수를 생성하는 방법으로 수정하였습니다.

2022-02-27 15:14 UTC, TaeKyeongKim commented on PokerGameApp/포커게임Tests/_________Tests.swift
> +class ___FILEBASENAMEASIDENTIFIER___: XCTestCase {
한국어가 포함된 테스트 타깃을 생성해서 그런것 같습니다.

2022-02-28 02:22 UTC, godrm commented
리팩토링을 하는 커밋들도 여러 개로 작게 나눠보세요.
이렇게 덩어리가 커지면 커밋 내부에 변화된 것들만 다시 되돌리기 무척 어렵습니다.

2022-02-28 02:22 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +        deck.shuffle()
속성으로 관리하는 구조도 나쁘지 않았는데, 이렇게 셔플만 deck을 주는 거라면 그냥 외부에서 해도 되는걸까요?

2022-02-28 02:23 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +    func dealCard(to player:Person , from deck : Deck) throws {
결국 Dealer의 주요 메소드 shuffleDeck() 와 dealCard() 모두 deck이 필요한거면
속성으로 갖고 있는 게 낫다고 판단해도 될 것 같습니다

2022-02-28 02:24 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/PokerGame.swift
> +    private(set) var players = [Person]()
players 배열을 담당하는 Players 혹은 Persons 같은 타입을 만들어 보는 것도 권해드립니다
그래야 players 배열에 추가하거나, 탐색하는 코드들이 다 하위 타입으로 이동하게 됩니다

2022-02-28 02:26 UTC, godrm commented
Players 하위 타입은 분리해보면 좋을 것 같습니다.

2022-02-28 02:26 UTC, merged